#!/usr/bin/escript
%% -*- erlang -*-
%%! -pa ebin

main([Arg]) ->
	{ok, Cwd} = file:get_cwd(),
	lists:map(
		fun(X) ->
			{ok, Msg} = file:read_file(X),
			{ok, Rtcps} = rtcp:decode(Msg),
			io:format("FILE: ~s, Rtcps: ~s~n", [X, rtp_utils:pp(Rtcps)]) 
		end,
		filelib:wildcard( Cwd ++ "/" ++ Arg ++ "rtcp_err.*.bin")
	).
